version: "3.7"

networks:
  default:
    external:
      name: cloudooo
  doonet:

volumes:
  odoo-data:
  odoo-testlogs:
  odoo-modules:
  psql:

services:
  odoo:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    
    restart: unless-stopped

    ports: ["8069:8069", "8072:8072"]

    volumes:
      # Host paths (.ssh configuration)
      - ~/.ssh/:/opt/odoo/.ssh/:cached
      # Named volumes
      - odoo-data:${ODOO_DATA_DIR}
      - odoo-testlogs:${ODOO_LOGS_DIR}
      - odoo-modules:${ODOO_EXTRA_ADDONS}
    depends_on:
      - db

    networks:
      doonet:
  # ------------------------
  db:
    image: kartoza/postgis:${PSQL_VERSION}
    restart: unless-stopped
    volumes:
      - psql:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata

    networks:
      doonet:
